import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatCurrency } from '@/features/transactions/utils/money';
import { getBudgetStatusColor, getBudgetStatusRingColor } from '../utils';
export function BudgetCard({ budget, currency = 'USD', onClick }) {
    const progress = Math.min(100, budget.progressPercent);
    const circumference = 2 * Math.PI * 36; // radius = 36
    const offset = circumference - (progress / 100) * circumference;
    return (_jsx("div", { onClick: onClick, className: `rounded-xl border border-slate-200 bg-white p-6 shadow-sm transition hover:shadow-md dark:border-slate-700 dark:bg-slate-800 ${onClick ? 'cursor-pointer' : ''}`, children: _jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "text-lg font-semibold text-slate-900 dark:text-slate-100", children: budget.name }), budget.categoryName && (_jsx("p", { className: "mt-1 text-sm text-slate-500 dark:text-slate-400", children: budget.categoryName })), _jsxs("div", { className: "mt-4 flex items-baseline gap-2", children: [_jsx("span", { className: "text-2xl font-bold text-slate-900 dark:text-slate-100", children: formatCurrency(budget.spentCents, currency) }), _jsxs("span", { className: "text-sm text-slate-500 dark:text-slate-400", children: ["/ ", formatCurrency(budget.amountCents, currency)] })] }), _jsxs("div", { className: "mt-2 flex items-center gap-2", children: [_jsx("span", { className: `text-sm font-medium ${getBudgetStatusColor(budget.status)}`, children: budget.status === 'over' ? 'Over budget' : `${progress.toFixed(0)}% used` }), _jsxs("span", { className: "text-xs text-slate-500 dark:text-slate-400", children: [formatCurrency(budget.remainingCents, currency), " remaining"] })] })] }), _jsxs("div", { className: "relative h-20 w-20", children: [_jsxs("svg", { className: "h-20 w-20 -rotate-90 transform", viewBox: "0 0 80 80", children: [_jsx("circle", { cx: "40", cy: "40", r: "36", stroke: "currentColor", strokeWidth: "6", fill: "none", className: "text-slate-200 dark:text-slate-700" }), _jsx("circle", { cx: "40", cy: "40", r: "36", stroke: "currentColor", strokeWidth: "6", fill: "none", strokeDasharray: circumference, strokeDashoffset: offset, strokeLinecap: "round", className: `transition-all duration-300 ${getBudgetStatusRingColor(budget.status)}` })] }), _jsx("div", { className: "absolute inset-0 flex items-center justify-center", children: _jsxs("span", { className: "text-sm font-semibold text-slate-700 dark:text-slate-300", children: [progress, "%"] }) })] })] }) }));
}
